[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"
ar = "aarch64-linux-android-ar"

[env]
CC_aarch64_linux_android = "aarch64-linux-android-clang"
CXX_aarch64_linux_android = "aarch64-linux-android-clang++"
