[package]
name = "hello-world-edge-function"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
edge-hive-wasm = { path = "../../../crates/edge-hive-wasm", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
